import type { Metadata } from "next";

import { JotaiProvider, NextUIProvider } from "./_layer";
import "./_shared/style/globals.css";
import { cn } from "./_shared/style";
import { pretendard } from "./_shared/style/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={cn(pretendard.variable, pretendard.className, "font-medium")}>
      <body>
        <JotaiProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
