import type { Metadata } from "next";

import { cx } from "~/shared/style";
import { pretendard } from "~/shared/style/fonts";

import { MainLayout } from "./_components";
import {
  JotaiProvider,
  MotionProvider,
  NextUIProvider,
} from "./_components/providers";

import "~/shared/style/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={cx(pretendard.variable, pretendard.className, "font-medium")}
    >
      <body>
        <MotionProvider>
          <JotaiProvider>
            <NextUIProvider>
              <MainLayout>{children}</MainLayout>
            </NextUIProvider>
          </JotaiProvider>
        </MotionProvider>
      </body>
    </html>
  );
}
